app/config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dashyboard.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

app/dashyboard/urls.py
from django.urls import path
from . import views


app_name = 'dashyboard'
urlpatterns = [
    path('', views.DeckListView.as_view(), name='all'),
    path('create/', views.DeckCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.DeckUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeckDeleteView.as_view(), name='delete'),
]

app/home/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'home'
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

app/dashyboard/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings

from taggit.managers import TaggableManager

class Decks(models.Model):
    name = models.CharField(max_length=100, validators=[MinLengthValidator(3)])
    description = models.TextField(max_length=500, validators=[MinLengthValidator(10)])
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

CARD_CHOICES = [
    ("1", "Basic"),
    ("2", "Reverse"),
    ("3", "Basic and Reverse "),
    ("4", "Type in Answer"),
]

class Cards(models.Model):
    deck = models.ForeignKey('Decks', on_delete=models.CASCADE, null=False)
    type = models.CharField(max_length=2, choices=CARD_CHOICES, default="1")
    front = models.CharField(max_length=1000, validators=[MinLengthValidator(3)])
    back = models.CharField(max_length=1000, validators=[MinLengthValidator(3)])
    detailed_info = models.CharField(max_length=100, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    def __str__(self):
        return f"{self.front} | {self.back}"

app/home/models.py
from django.db import models

# Create your models here.

app/dashyboard/forms.py
import django.forms as forms
from .models import Decks, Cards

class CreateForm(forms.ModelForm):
    class Meta:
        model = Decks
        fields = ["name", "description"]

    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        if commit:
            instance.save()

        return instance

class CardCreateForm(forms.ModelForm):
    class Meta:
        model = Cards
        fields = ["deck", "type", "front", "back", "detailed_info", "tags"]

app/dashyboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, View, CreateView, \
    UpdateView, DeleteView

from .forms import CreateForm, CardCreateForm
from .models import Decks
from .owners import OwnerListView, OwnerDeleteView, OwnerUpdateView, \
    OwnerCreateView


class DeckListView(OwnerListView):
    model = Decks
    template_name = 'Dashyboard/decks_list.html'
    success_url = reverse_lazy('dashyboard:all')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form'] = CardCreateForm()

        return ctx

class DeckCreateView(LoginRequiredMixin, View):
    template_name = 'dashyboard/decks_form.html'
    success_url = reverse_lazy('dashyboard:all')

    def get(self, request):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = CreateForm(request.POST)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        deck = form.save(commit=False)
        deck.owner = request.user
        deck.save()
        return redirect(self.success_url)


class DeckUpdateView(LoginRequiredMixin, View):
    template_name = 'dashyboard/decks_form.html'
    success_url = reverse_lazy('dashyboard:all')

    def get(self, request, pk):
        deck = get_object_or_404(Decks, pk=pk, owner=self.request.user)
        form = CreateForm(instance=deck)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        deck = get_object_or_404(Decks, pk=pk, owner=self.request.user)
        form = CreateForm(request.POST, instance=deck)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        deck.save()
        return redirect(self.success_url)


class DeckDeleteView(OwnerDeleteView):
    model = Decks
    success_url = reverse_lazy('dashyboard:all')

app/home/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

app/dashyboard/templates/dashyboard/decks_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<div>
    <p> Are you sure you want to delete?</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Yes, Delete">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'dashyboard:all' %}'; return false">
    </form>
</div>
{% endblock %}

app/dashyboard/templates/dashyboard/decks_form.html
{% extends 'base_menu.html' %}
{% block content %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
        <input type="reset" value="Clear">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'dashyboard:all' %}'">
    </form>
</div>
{% endblock %}

app/dashyboard/templates/dashyboard/decks_list.html
{% extends 'base_menu.html' %}
{% block content %}
{% load static %}
<h1>Deck List</h1>
<div id="deck_list">
{% if decks_list %}
    <ul>
        {% for deck in decks_list %}
        <li>
            <strong> {{ deck.name }} </strong>
            <button id="addCard"> Add Cards </button>
            <a href="{% url 'dashyboard:update' deck.id %}"> Edit Deck </a>
            <a href="{% url 'dashyboard:delete' deck.id %}"> Delete Deck </a>
        </li>
        <span> {{ deck.description }} </span>
        {% endfor %}
    </ul>
    <div id="myModal" class="modal">
      <div class="modal-content">
        <span class="close">&times;</span>
        <form id="popupForm" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
      </div>
    </div>
{% else %}
    <div>No Decks Yet!!</div>
{% endif %}
</div>
<div id="deck_form">
    <a href="{% url 'dashyboard:create' %}">Add Deck</a>
    <a href="#">Import Deck</a>
</div>
{% endblock %}

app/home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% load static %}
<link rel="stylesheet" href="{% static 'css/add_card.css' %}">
{% block head %} {% endblock %}

</head>
<body>
{% block navbar %} {% endblock %}
<div class="container">
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
<script src="{% static 'js/add_card.js' %}"></script>
</body>
</html>

app/home/templates/base_menu.html
{% extends 'base_bootstrap.html' %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{ settings.APP_NAME }}</a>
    <ul class="navbar-nav">
      {% url 'dashyboard:all' as x %}
      <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="#" role="button">Add Cards</a></li>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li>
         <a class="nav-link" href="#">Profile</a>
      </li>
      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="rightnavDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img style="width: 25px;"/><b class="caret"></b>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
            <li>
                <form action="{% url 'logout' %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="">
                    <button class="dropdown-item btn btn-link" type="submit">Logout</button>
                </form>
            </li>
        </ul>
       </li>
       {% else %}
       <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={% url 'dashyboard:all' %}">Login</a></li>
       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

app/home/templates/home/logout.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
<!--    <p>You have successfully logged out!!</p>-->
<!--    <a href="{% url 'login' %}"> Click here to login back again!! </a>-->
<!--</body>-->
<!--</html>-->